<?php

namespace App\Repositories\Eloquent;

use App\Models\Customer;
use App\Repositories\CustomerRepositoryInterface;

class CustomerRepository extends BaseRepository implements CustomerRepositoryInterface
{
    public function __construct(Customer $model)
    {
        parent::__construct($model);
    }

    //Lấy tất cả khách hàng có phân trang mỗi trang 6kh
    public function getAll()
    {
        return $this->model->orderby('customer_id', 'DESC')->paginate(6);
    }

    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    //Add new customer account
    public function create($request)
    {
        return $this->model->newModelQuery()->create($request);
    }

    public function update($id, array $attributes)
    {
        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }


}